#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot paper-ready classwise F1-score comparison across LCZ models.

The script reads classwise_accuracy.csv files generated by
3_accuracy_from_confusion_matrix.py and creates:
  1) grouped classwise F1-score bar chart
  2) merged classwise F1 comparison CSV
  3) overall metric summary table as CSV and paper-style PNG

Example
-------
python code/4_plot_classwise_f1_comparison.py \
  --model "RS-CNN (Baseline)=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/cnn_rs_baseline_accuracy/classwise_accuracy.csv" \
  --model "RasterConcat-CNN=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/cnn_rs_raster_building_accuracy/classwise_accuracy.csv" \
  --model "BuildingVisual-CNN=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/cnn_rs_building_visual_encoder_accuracy/classwise_accuracy.csv" \
  --model "BGF-LCZNet (Ours)=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/v7_accuracy/classwise_accuracy.csv" \
  --summary "RS-CNN (Baseline)=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/cnn_rs_baseline_accuracy/summary_accuracy.csv" \
  --summary "RasterConcat-CNN=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/cnn_rs_raster_building_accuracy/summary_accuracy.csv" \
  --summary "BuildingVisual-CNN=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/cnn_rs_building_visual_encoder_accuracy/summary_accuracy.csv" \
  --summary "BGF-LCZNet (Ours)=/mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/v7_accuracy/summary_accuracy.csv" \
  --out_dir /mnt/disk1/workspace_jym/LCZ/work_dirs/analysis/model_f1_comparison \
  --title "Classwise LCZ classification performance"
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


LCZ_SHORT_CODE = {
    101: "A",
    102: "B",
    103: "C",
    104: "D",
    105: "E",
    106: "F",
    107: "G",
}

DEFAULT_COLORS = ["#BDBDBD", "#8FA8BF", "#D62728", "#7A5195", "#54A24B", "#ECA82C"]

MODEL_METADATA = {
    "RS-CNN (Baseline)": ("RS", "Single", "-"),
    "RasterConcat-CNN": ("RS + Building", "Single", "Raster"),
    "BuildingVisual-CNN": ("RS + Building", "Dual", "Raster"),
    "BGF-LCZNet (Ours)": ("RS + Building", "Dual", "Graph"),
}


def model_color(model_name, model_index):
    """Keep baselines subdued and highlight the proposed model."""
    normalized = model_name.lower().replace("-", "_")
    if "proposed" in normalized or "bgf" in normalized or "ours" in normalized or normalized in {"v7", "sf"}:
        return "#D62728"
    if "rs_cnn" in normalized or "cnn_rs" in normalized or "baseline" in normalized:
        return "#C7C7C7"
    if "rasterconcat" in normalized or "raster" in normalized:
        return "#A9B8C6"
    if "buildingvisual" in normalized or "visual" in normalized:
        return "#7F9DB9"
    return DEFAULT_COLORS[model_index % len(DEFAULT_COLORS)]


def parse_named_paths(values, argument_name):
    parsed = []
    for value in values or []:
        if "=" not in value:
            raise ValueError(f"{argument_name} must use NAME=/path/to/file.csv")
        name, path = value.split("=", 1)
        parsed.append((name, Path(path)))
    return parsed


def class_label(code):
    code = int(code)
    return f"LCZ{LCZ_SHORT_CODE.get(code, code)}"


def load_classwise(model_items):
    frames = []
    expected_codes = None
    for model_name, path in model_items:
        if not path.exists():
            raise FileNotFoundError(path)
        frame = pd.read_csv(path)
        required = {"class_code", "F1"}
        if not required.issubset(frame.columns):
            raise ValueError(f"{path} must contain columns {sorted(required)}")
        frame = frame.copy()
        frame["class_code"] = frame["class_code"].astype(int)
        codes = frame["class_code"].tolist()
        if expected_codes is None:
            expected_codes = codes
        elif codes != expected_codes:
            raise ValueError(f"Class order mismatch in {path}: {codes} != {expected_codes}")
        frame["model"] = model_name
        frames.append(frame)
    return expected_codes, pd.concat(frames, ignore_index=True)


def load_summaries(summary_items, model_names):
    summaries = {}
    for model_name, path in summary_items:
        if not path.exists():
            raise FileNotFoundError(path)
        frame = pd.read_csv(path)
        if len(frame) != 1:
            raise ValueError(f"Expected one summary row in {path}")
        summaries[model_name] = frame.iloc[0].to_dict()
    unknown = set(summaries) - set(model_names)
    if unknown:
        raise ValueError(f"Summary model names do not match --model names: {sorted(unknown)}")
    return summaries


def plot_classwise_f1(class_codes, comparison, model_names, summaries, out_png, title, dpi):
    n_classes = len(class_codes)
    n_models = len(model_names)
    x = np.arange(n_classes)
    group_width = 0.78
    bar_width = group_width / n_models
    offsets = (np.arange(n_models) - (n_models - 1) / 2) * bar_width

    fig_height = 7.8 if summaries else 6.4
    fig, ax = plt.subplots(figsize=(max(12, n_classes * 1.05), fig_height))

    model_values = []
    bars_by_model = []
    for model_index, model_name in enumerate(model_names):
        values = comparison.loc[comparison["model"] == model_name, "F1"].to_numpy(dtype=float)
        model_values.append(values)
        bars = ax.bar(
            x + offsets[model_index],
            values,
            width=bar_width * 0.92,
            color=model_color(model_name, model_index),
            edgecolor="white",
            linewidth=0.6,
            label=model_name,
            zorder=3,
        )
        bars_by_model.append(bars)

    value_matrix = np.stack(model_values, axis=0)
    best_indices = np.argmax(value_matrix, axis=0)
    for class_index, model_index in enumerate(best_indices):
        bar = bars_by_model[model_index][class_index]
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            min(bar.get_height() + 0.025, 1.06),
            "*",
            ha="center",
            va="bottom",
            fontsize=14,
            fontweight="bold",
            color="#222222",
        )

    ax.set_xticks(x, [class_label(code) for code in class_codes], fontsize=10)
    ax.set_ylim(0, 1.1)
    ax.set_yticks(np.arange(0, 1.01, 0.1))
    ax.set_ylabel("F1-score", fontsize=11)
    ax.set_title(title, fontsize=15, fontweight="bold", pad=14)
    ax.grid(axis="y", color="#d9d9d9", linewidth=0.8, zorder=0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.10),
        ncol=n_models,
        frameon=False,
        fontsize=10,
    )

    if summaries:
        metric_names = [("OA", "OA"), ("Macro_F1", "Macro-F1"), ("Weighted_F1", "Weighted-F1"), ("Kappa", "Kappa")]
        rows = []
        for model_name in model_names:
            summary = summaries.get(model_name, {})
            rows.append([
                model_name,
                *[
                    f"{float(summary[key]) * 100:.2f}%" if key in summary else "-"
                    for key, _ in metric_names
                ],
            ])
        table = ax.table(
            cellText=rows,
            colLabels=["Model"] + [label for _, label in metric_names],
            cellLoc="center",
            colLoc="center",
            bbox=[0.13, -0.43, 0.74, 0.23],
        )
        table.auto_set_font_size(False)
        table.set_fontsize(8.5)
        for (row, col), cell in table.get_celld().items():
            cell.set_edgecolor("#b0b0b0")
            cell.set_linewidth(0.6)
            if row == 0:
                cell.set_facecolor("#e8e8e8")
                cell.set_text_props(fontweight="bold")

    fig.text(
        0.99,
        0.012,
        "* Highest F1-score for each LCZ class",
        ha="right",
        va="bottom",
        fontsize=8.5,
        color="#555555",
    )
    bottom = 0.30 if summaries else 0.19
    fig.subplots_adjust(bottom=bottom, left=0.08, right=0.98, top=0.90)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def build_overall_table(summaries, model_names):
    rows = []
    for model_name in model_names:
        summary = summaries.get(model_name)
        if summary is None:
            continue
        input_type, encoder_type, building_representation = MODEL_METADATA.get(
            model_name, ("-", "-", "-")
        )
        rows.append({
            "Method": model_name,
            "Input": input_type,
            "Encoder type": encoder_type,
            "Building representation": building_representation,
            "OA": float(summary["OA"]),
            "Macro-F1": float(summary["Macro_F1"]),
            "Weighted-F1": float(summary["Weighted_F1"]),
        })
    return pd.DataFrame(rows)


def plot_overall_table(table_df, out_png, caption, dpi):
    metric_columns = ["OA", "Macro-F1", "Weighted-F1"]
    best_values = {column: table_df[column].max() for column in metric_columns}

    fig, ax = plt.subplots(figsize=(15.5, 4.2))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    ax.text(
        0.02,
        0.93,
        caption,
        ha="left",
        va="top",
        fontsize=13,
        fontweight="bold",
        wrap=True,
    )

    cell_text = []
    for _, row in table_df.iterrows():
        cell_text.append([
            row["Method"],
            row["Input"],
            row["Encoder type"],
            row["Building representation"],
            *[f"{float(row[column]):.4f}" for column in metric_columns],
        ])

    column_labels = [
        "Method", "Input", "Encoder type", "Building representation", *metric_columns
    ]
    table = ax.table(
        cellText=cell_text,
        colLabels=column_labels,
        cellLoc="center",
        colLoc="center",
        bbox=[0.02, 0.18, 0.96, 0.58],
        colWidths=[0.22, 0.15, 0.17, 0.23, 0.10, 0.12, 0.14],
    )
    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1, 1.35)

    n_rows = len(table_df)
    n_cols = len(column_labels)
    for (row_index, col_index), cell in table.get_celld().items():
        cell.set_facecolor("white")
        cell.set_edgecolor("#555555")
        cell.set_linewidth(0.0)
        if row_index == 0:
            cell.set_text_props(fontweight="bold")
            cell.visible_edges = "B"
            cell.set_linewidth(0.8)
        elif row_index == n_rows:
            cell.visible_edges = "B"
            cell.set_linewidth(1.1)

    for row_index, (_, row) in enumerate(table_df.iterrows(), start=1):
        table[(row_index, 0)].set_text_props(fontweight="normal")
        for metric_index, column in enumerate(metric_columns, start=4):
            if np.isclose(float(row[column]), best_values[column]):
                table[(row_index, metric_index)].set_text_props(fontweight="bold")

    ax.plot([0.02, 0.98], [0.79, 0.79], color="black", linewidth=1.2, transform=ax.transAxes)
    ax.text(
        0.5,
        0.09,
        "The highest value for each accuracy metric is shown in bold.",
        ha="center",
        va="center",
        fontsize=9.5,
        color="#444444",
    )
    fig.savefig(out_png, dpi=dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", action="append", required=True, help="NAME=/path/to/classwise_accuracy.csv")
    parser.add_argument("--summary", action="append", default=None, help="NAME=/path/to/summary_accuracy.csv")
    parser.add_argument("--out_dir", required=True)
    parser.add_argument("--title", default="Classwise LCZ classification performance")
    parser.add_argument(
        "--table_caption",
        default="Overall accuracy assessment results for the four LCZ classification methods.",
    )
    parser.add_argument("--png_name", default="classwise_f1_comparison.png")
    parser.add_argument("--dpi", type=int, default=300)
    args = parser.parse_args()

    model_items = parse_named_paths(args.model, "--model")
    summary_items = parse_named_paths(args.summary, "--summary")
    model_names = [name for name, _ in model_items]
    if len(set(model_names)) != len(model_names):
        raise ValueError("--model names must be unique")

    class_codes, comparison = load_classwise(model_items)
    summaries = load_summaries(summary_items, model_names)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    pivot = comparison.pivot(index="class_code", columns="model", values="F1").reset_index()
    pivot = pivot[["class_code"] + model_names]
    pivot.to_csv(out_dir / "classwise_f1_comparison.csv", index=False, encoding="utf-8-sig")

    out_png = out_dir / args.png_name
    plot_classwise_f1(
        class_codes=class_codes,
        comparison=comparison,
        model_names=model_names,
        summaries=summaries,
        out_png=out_png,
        title=args.title,
        dpi=args.dpi,
    )

    if summaries:
        overall_table = build_overall_table(summaries, model_names)
        overall_csv = out_dir / "overall_accuracy_table.csv"
        overall_png = out_dir / "overall_accuracy_table.png"
        overall_table.to_csv(overall_csv, index=False, encoding="utf-8-sig", float_format="%.4f")
        plot_overall_table(overall_table, overall_png, args.table_caption, args.dpi)

    print("saved:", out_png)
    print("saved:", out_dir / "classwise_f1_comparison.csv")
    if summaries:
        print("saved:", overall_csv)
        print("saved:", overall_png)


if __name__ == "__main__":
    main()
